 mkoctfile ocENclose.cc -L. -lepanet -I.
 mkoctfile ocENcloseH.cc -L. -lepanet -I.
 mkoctfile ocENcloseQ.cc -L. -lepanet -I.
 mkoctfile ocENepanet.cc -L. -lepanet -I.
 mkoctfile ocENgetcount.cc -L. -lepanet -I.
 mkoctfile ocENgeterror.cc -L. -lepanet -I.
 mkoctfile ocENgetflowunits.cc -L. -lepanet -I.
 mkoctfile ocENgetlinkid.cc -L. -lepanet -I.
 mkoctfile ocENgetlinkindex.cc -L. -lepanet -I.
 mkoctfile ocENgetlinknodes.cc -L. -lepanet -I.
 mkoctfile ocENgetlinktype.cc -L. -lepanet -I.
 mkoctfile ocENgetlinkvalue.cc -L. -lepanet -I.
 mkoctfile ocENgetnodeid.cc -L. -lepanet -I.
 mkoctfile ocENgetnodeindex.cc -L. -lepanet -I.
 mkoctfile ocENgetnodetype.cc -L. -lepanet -I.
 mkoctfile ocENgetnodevalue.cc -L. -lepanet -I.
 mkoctfile ocENgetpatternid.cc -L. -lepanet -I.
 mkoctfile ocENgetpatternindex.cc -L. -lepanet -I.
 mkoctfile ocENgetpatternlen.cc -L. -lepanet -I.
 mkoctfile ocENgetpatternvalue.cc -L. -lepanet -I.
 mkoctfile ocENinitH.cc -L. -lepanet -I.
 mkoctfile ocENinitQ.cc -L. -lepanet -I.
 mkoctfile ocENnextH.cc -L. -lepanet -I.
 mkoctfile ocENnextQ.cc -L. -lepanet -I.
 mkoctfile ocENopen.cc -L. -lepanet -I.
 mkoctfile ocENopenH.cc -L. -lepanet -I.
 mkoctfile ocENopenQ.cc -L. -lepanet -I.
 mkoctfile ocENreport.cc -L. -lepanet -I.
 mkoctfile ocENresetreport.cc -L. -lepanet -I.
 mkoctfile ocENrunH.cc -L. -lepanet -I.
 mkoctfile ocENrunQ.cc -L. -lepanet -I.
 mkoctfile ocENsaveH.cc -L. -lepanet -I.
 mkoctfile ocENsavehydfile.cc -L. -lepanet -I.
 mkoctfile ocENsetlinkvalue.cc -L. -lepanet -I.
 mkoctfile ocENsetnodevalue.cc -L. -lepanet -I.
 mkoctfile ocENsetpattern.cc -L. -lepanet -I.
 mkoctfile ocENsetpatternvalue.cc -L. -lepanet -I.
 mkoctfile ocENsetstatusreport.cc -L. -lepanet -I.
 mkoctfile ocENsolveH.cc -L. -lepanet -I.
 mkoctfile ocENsolveQ.cc -L. -lepanet -I.
